from sqlmodel import SQLModel, Field, Text, Numeric, LargeBinary, TIMESTAMP
from datetime import datetime

class Item(SQLModel, table=True):
  __tablename__ = "tbl_item"

  kodeitem: str = Field(primary_key=True, max_length=100)
  namaitem: str|None = Field(sa_type=Text)
  jenis: str|None = Field(max_length=50)
  tipe: str|None = Field(default='Y', max_length=15)
  matauang: str|None = Field(max_length=50)
  serial: str|None = Field(default='N', max_length=15)
  konsinyasi: str|None = Field(default='N', max_length=15)
  stokmin: float|None = Field(default=0, sa_type=Numeric(20, 3))
  sistemhargajual: str|None = Field(default='J', max_length=1)
  opsihargajual: bool|None = Field(default=True)
  rak: str|None = Field(max_length=100)
  satuan: str|None = Field(max_length=50)
  hargapokok: float|None = Field(default=0, sa_type=Numeric(20, 3))
  prhargajual1: float|None = Field(default=0, sa_type=Numeric(20, 3))
  hargajual1: float|None = Field(default=0, sa_type=Numeric(20, 3))
  keterangan: str|None = Field(sa_type=Text)
  supplier1: str|None = Field(max_length=50)
  gambar: bytes|None = Field(sa_type=LargeBinary)
  statusjual: str|None = Field(max_length=15)
  acc_hpp: str|None = Field(max_length=30)
  acc_pendapatan: str|None = Field(max_length=30)
  acc_persediaan: str|None = Field(max_length=30)
  acc_jasa: str|None = Field(max_length=30)
  acc_noninventory: str|None = Field(max_length=30)
  statushapus: str|None = Field(max_length=15)
  tmphp: str|None = Field(default=0, sa_type=Numeric(20, 3))
  tmpjml: str|None = Field(default=0, sa_type=Numeric(20, 3))
  tmpnilai: str|None = Field(default=0, sa_type=Numeric(20, 3))
  dateupd: datetime|None = Field(sa_type=TIMESTAMP)
  dept: str|None = Field(max_length=50)
  stok: float|None = Field(default=0, sa_type=Numeric(20, 3))
  merek: str|None = Field(max_length=50)
  nonpoint: str|None = Field(default='N', max_length=15)
  opt: str|None = Field(max_length=10)
  brgjasa_refcode: str|None = Field(max_length=10)
