from sqlmodel import SQLModel, Field, Numeric, Text
from datetime import datetime

class PesanHD(SQLModel, table=True):
  __tablename__ = "tbl_pesanhd"

  notransaksi: str = Field(primary_key=True, max_length=50)
  kodekantor: str|None = Field(max_length=50)
  kantortujuan: str|None = Field(max_length=50)
  tanggal: datetime|None = Field()
  tipe: str|None = Field(max_length=20)
  tanggalkirim: datetime|None = Field()
  jenis: str|None = Field(max_length=5)
  kodesupel: str|None = Field(max_length=50)
  kodesales: str|None = Field(max_length=50)
  kodesales2: str|None = Field(max_length=50)
  kodesales3: str|None = Field(max_length=50)
  kodesales4: str|None = Field(max_length=50)
  matauang: str|None = Field(max_length=50)
  rate: float|None = Field(default=0, sa_type=Numeric(35,20))
  keterangan: str|None = Field(sa_type=Text)
  komisi1: float|None = Field(default=0, sa_type=Numeric(20, 3))
  komisi2: float|None = Field(default=0, sa_type=Numeric(20, 3))
  komisi3: float|None = Field(default=0, sa_type=Numeric(20, 3))
  komisi4: float|None = Field(default=0, sa_type=Numeric(20, 3))
  totalitem: float|None = Field(default=0, sa_type=Numeric(20, 3))
  totalterima: float|None = Field(default=0, sa_type=Numeric(20, 3))
  subtotal: float|None = Field(default=0, sa_type=Numeric(20, 3))
  potfaktur: float|None = Field(default=0, sa_type=Numeric(25, 10))
  pajak: float|None = Field(default=0, sa_type=Numeric(20, 3))
  biayalain: float|None = Field(default=0, sa_type=Numeric(20, 3))
  totalakhir: float|None = Field(default=0, sa_type=Numeric(20, 3))
  biaya_msk_total: bool|None = Field()
  user1: str|None = Field(max_length=50)
  user2: str|None = Field(max_length=50)
  dateupd: datetime|None = Field()
  potnomfaktur: float|None = Field(default=0, sa_type=Numeric(20, 3))
  prpajak: float|None = Field(default=0, sa_type=Numeric(10, 3))
  dppesanan: float|None = Field(default=0, sa_type=Numeric(20, 3))
  dppesananbyr: float|None = Field(default=0, sa_type=Numeric(20, 3))
  acc_dppesanan: str|None = Field(max_length=30)
  acc_dpkas: str|None = Field(max_length=30)
  jenis_pajak: str|None = Field(max_length=10)